### ISSUE TITLE
onComplete does not use current state

### ISSUE THREAD

**Issue by riteley** [vydimitrov/react-countdown-circle-timer#100]
Thank you for your work on this package.

I want to alter a state upon timer completion. However, it seems as though onComplete uses the state from when the timer first starts. See example [here](https://codesandbox.io/s/fervent-sun-ez03d?file=/src/App.tsx) - code is below too.

The counter can be incremented using the + button. If the + button is pressed while timer is running, the counter increments. On completion, I want the counter to be incremented again from its current value. Instead, it seems to revert to the initial state and then increments that. Is this intended behavior?

```
import * as React from "react";
import { CountdownCircleTimer } from "react-countdown-circle-timer";
import "./styles.css";

export default function App() {
  const [counter, setCounter] = React.useState(0);

  const inc = () => {
    setCounter(counter + 1);
  };

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <button onClick={inc}>+</button>
      <h2>Counter {counter}</h2>
      <CountdownCircleTimer
        isPlaying
        durationSeconds={4}
        onComplete={() => {
          inc();
          return [true, 100];
        }}
        colors={[
          ["#004777", 0.33],
          ["#F7B801", 0.33]
        ]}
      />
    </div>
  );
}
```

**Comment by vydimitrov** [comment]
Hey @riteley, yup, this is a known limitation of `onComplete`, since it is called from the `requestAnimationFrame` loop [here](https://github.com/vydimitrov/use-elapsed-time/blob/master/src/hooks/useElapsedTime.js#L51). I am planning to rewrite the hook to TypeScript and fix this limitation but somehow I can not find time for it.

On the other hand, if you want to [set state that relise on the previous state](https://reactjs.org/docs/hooks-reference.html#functional-updates) then you need to use it as a function, like so
```js
const inc = () => {
    setCounter(prevCounter => prevCounter + 1);
  };
```
This way it is going to work regardless of the onComplete not updating.

**Comment by riteley** [comment]
Thank you, I didn't know you could do that with setState - works great!
