### ISSUE TITLE
Cannot change wrapper style

### ISSUE THREAD

**Issue by ionutvs** [vydimitrov/react-countdown-circle-timer#18]
There seems no way to change the wrapper style..this would be a nice feature :) https://github.com/vydimitrov/react-countdown-circle-timer/blob/master/packages/shared/utils/styles.js

**Comment by vydimitrov** [comment]
Hey @ionutvs, what is the thing you are trying to achieve? I might be able to help you.

**Comment by ionutvs** [comment]
I tried to align it horizontally, but since it won't accept any styles to the main div, i needed to use 2 divs, like so: 
```
<CountDownWrapper>
          <CountDownAligner>
            <CountdownCircleTimer
              isPlaying
              duration={6}
              colors={[['#008C99']]}
            >
              {({ remainingTime, animatedColor }) => (
                      <Text style={{ color: animatedColor }}>
                          {remainingTime}
                      </Text>
              )}
            </CountdownCircleTimer>
          </CountDownAligner>
        </CountDownWrapper>
```

where CountdownWrapper is 
```
const CountDownWrapper = styled.div
  width: 100%;
  text-align: center;
  padding-top: 1%;
`;
```


and CountDownAligner is 

```
const CountDownAligner = styled.div`
  display: inline-block;
  background-color: #E2EFF2;
  border-radius: 100%;
`;
```

**Comment by ionutvs** [comment]
It works this way, it was a "nice-to-have" request :D Thanks!

**Comment by vydimitrov** [comment]
Hey, I am happy you manage to do it. 

By reviewing your code, it seems you are trying to center the countdown timer, with `text-align: center;` for the wrapper and `display: inline-block;` for the aligner. In this case I would use a single `div` with `display: flex;`, which it would do the job. Other then that, all styles for positioning an element should go to the wrapper, thus the countdown timer should not be aware of any position styles. 

I will keep this request in mind and if it appear that more people would need it I will add it. Otherwise, I would prefer to keep the component's API as clean as possible :)
