### ISSUE TITLE
Set initial elapsed time?

### ISSUE THREAD

**Issue by headzoo** [vydimitrov/react-countdown-circle-timer#2]
I stumbled upon this project when a client requested a count time timer that looks like this.

![Screenshot-countdown](https://user-images.githubusercontent.com/707209/70857481-2e243b00-1ebd-11ea-8c3f-3ba79a059e73.png)

The react-countdown-circle-time works great but would be even better if I could show some amount of time already elapsed when the component mounts. Seems this would be a dual request with react-countdown-circle-time and use-elapsed-time. Which would need to support an initial elapsed time config option. While I can work with seconds, it would be great if the component supported a unit of time other than seconds out of the box.

**Comment by vydimitrov** [comment]
Hi @headzoo, I will add a new prop to set the initial elapsed time. It seems something that people may need. I will try to add the prop by the end of next week. 

One thing that I am not sure though, if we repeat the timer then we should start from 0 again instead of the "initial elapsed time". Is there a case where one will need to start from the "initial elapsed time" when the timer is repeated?

I agree that would be nice to have support out of the box for different time formats, but that is going to complicate the API to much for something that you can do by simple math. Like below:

- minutes (1 hour/ 60 minutes)
`durationSeconds: 3600`
`renderTime: value => Math.ceil(value * 0.0166667) minutes`

- hours (1 day / 24 hours)
`durationSeconds: 86400`
`renderTime: value => Math.ceil(value * 0,000277778) hours`

**Comment by vydimitrov** [comment]
Hey, I did add a new prop `startAt` that can be used to shift the initial start time. Hope it helps.
