### ISSUE TITLE
 Rendering on the OnComplete

### ISSUE THREAD

**Issue by diegocruzfernandes** [vydimitrov/react-countdown-circle-timer#23]
Hi Vydimitrov

need help

I would like to use CountdownCircleTime as a time counter, instead of having to implement a setInterval.
So, what I need is that every time a onCompleted, activate a method that updates my page.
So that I can control how many times the page has been updated.

I have a problem when rendering onComplete.
I need to define the variable with useState, as soon as there is a complete loop (onComplete), however, at this moment, react complains saying:

Warning: Cannot update a component ('Home') while rendering a different componet ('CountdownCircleTime'). To locate the bad setState() call insede 'CountDownCircleTime'.

react: 16.12.0,
react-dom: 16.12.0,
react-countdown-circle-timer: 2.1.2

```
import React, { useEffect, useState } from 'react';
import { CountdownCircleTimer } from 'react-countdown-circle-timer';

function Home() {
  const [count, setCount] = useState(1);
  const [play, setPlay] = useState(true);

  const updateComponentes = () => {
    console.log('Refresh my components, count:', count);
  };

  const stopCount = () => {
    // does not execute this method
    setPlay(false);
  };

  useEffect(() => {
    if (count < 3) updateComponentes();
    else stopCount();
  }, [count]);

  return (
    <CountdownCircleTimer
      isPlaying={play}
      duration={8}
      colors={[
        ['#2185d0', 0.5],
        ['#2185d0', 0.5]
      ]}
      onComplete={() => {
        setCount(count + 1);
        return [true, 1002]; // on the second lap, the component breaks and does not execute that line
      }}
      size={25}
      strokeWidth={4}
    />
  );
}

export default Home;
```
Thank you for your attention

**Comment by diegocruzfernandes** [comment]
I'm sorry, I didn't see that there is already an open issue reporting the same problem:

https://github.com/vydimitrov/react-countdown-circle-timer/issues/6

**Comment by diegocruzfernandes** [comment]
I'm sorry, I didn't see that there is already an open issue reporting the same problem
https://github.com/vydimitrov/react-countdown-circle-timer/issues/6

**Comment by vydimitrov** [comment]
Hey @diegocruzfernandes , thanks for reporting the issue. This time around I was able to reproduce it. The issue comes from changing the `isPlaying` within the `onComplete` callback. I will have a fix for it soon. 

In your case I would recommend returning `[false]` from the `onComplete` handler to stop the loop when you need to do so. Please refer to the codesandbox below:
https://codesandbox.io/s/nice-benz-t1cg0?file=/src/index.js

Also some additional recommendation, if you don't need to transition colors during the countdown you can simply do this `colors={[[#2185d0]]}`
