### ISSUE TITLE
Adding Minutes : Seconds to the timer.

### ISSUE THREAD

**Issue by HumayounBaig** [vydimitrov/react-countdown-circle-timer#34]
hey there great repo btw,

So i was implementing it but i need a timer for something like remaining time (i.e. Picture attached). Please let me know if this would be possible.
![image](https://user-images.githubusercontent.com/32910163/87303305-690e5000-c52c-11ea-8a04-5e3290e22b84.png)

**Comment by vydimitrov** [comment]
Hey @HumayounBaig, you are the right place. Of course you can do it .... you will need just to format the remaining time. Here is one possible solution, check the codesandbox- https://codesandbox.io/s/vigorous-easley-rh33d?file=/src/index.js

**Comment by HumayounBaig** [comment]
hey @vydimitrov thanks it worked great.
i'll suggest adding this example in docs would make it much easier to find.

**Comment by vydimitrov** [comment]
Sure thing, I will add a few exmaples on how to format remaining time. I am closing this issue, let me know if you need any additional help.

**Comment by HumayounBaig** [comment]
thanks @vydimitrov,
one last thing i am having issue with updating the remaining time i.e. adding or removing from it. I am updating the state used for 'duration' but the timer doesn't refresh / update reflecting the updated duration state.
Is there any way to update the timer programatically.

![image](https://user-images.githubusercontent.com/32910163/87431342-ece53c80-c5ff-11ea-993a-55148b8dc225.png)

**Comment by vydimitrov** [comment]
Changing the `duration` and `initialRemainingTime` is not really possible once the component is mounted because it is very error prone. One way to go around is to pass a new `key` prop to the component, which will cause the component to render and start over when you want to change one of the two props. You can read more [here](https://github.com/vydimitrov/react-countdown-circle-timer/tree/master/packages/web#restart-timer-at-any-given-time).

**Comment by HumayounBaig** [comment]
@vydimitrov thanks alot adding `key` prop did the trick for me. 👍
