### ISSUE TITLE
isPlaying not updating.

### ISSUE THREAD

**Issue by maormagori** [vydimitrov/react-countdown-circle-timer#53]
I'm using React not React-native btw.
When passing a refrence to isPlaying the timer is not effected when the refrence value changes. Is there any way to pause/resume the timer otherwise?

**Comment by vydimitrov** [comment]
Hey @maormagori, changing the value of `isPlaying` to true/false should play/paused the timer. Can share a Codesandbox where you reproduce the issue?

**Comment by vydimitrov** [comment]
Hey @maormagori, I preped a quick demo for you here - https://codesandbox.io/s/morning-surf-q5exp?file=/src/index.js
Let me know if you have any other questions.

**Comment by Nishant-Pall** [comment]
Hey, I was having a similar issue with changing the value of isPlaying on an onClick handler call on a button. I'm using setState to change the value whenever I click the button so that the timer stops. Is this the right way because it doesn't seem to be working. I'm sharing snippets from my code. I would really appreciate your help.

`
state = {
		isClicked: false
	}

startTimer() {
		this.setState({
			isClicked: true
		})
	}

<button type="button" onClick={this.startTimer}>Listen</button>

<CountdownCircleTimer
							isPlaying={this.isClicked}
							duration={10}
							colors={[["#004777", 0.33], ["#F7B801", 0.33], ["#A30000"]]}
							onComplete={() => [false, 1000]}
							strokeWidth={8}
							size={75}
						>
							{this.renderTime}
						</CountdownCircleTimer>

`

**Comment by vydimitrov** [comment]
Did you bind `this.startTimer`? Why do you use class components?

**Comment by Nishant-Pall** [comment]
Yes, I did bind ```this.startTimer```. I'm using class components because it's required in the application. This is just a part of the whole code.

**Comment by vydimitrov** [comment]
`isPlaying={this.isClicked}` should `isPlaying={this.state.isClicked}`

**Comment by Nishant-Pall** [comment]
Oh right, it's a state. Thank you so much.
