### ISSUE TITLE
Cannot setState in onComplete (can causes looping)

### ISSUE THREAD

**Issue by pkm52000** [vydimitrov/react-countdown-circle-timer#6]
If you setState in the callback provided to the onComplete prop results in "cannot update during an existing state transition" error.

I have experienced brief forever looping when setting state multiple times in this callback.

Version: 1.05 and 1.1.0

**Comment by vydimitrov** [comment]
Hey, I am not able to reproduce it, please refer to the Codesandbox here- https://codesandbox.io/s/gracious-dust-dwptd

Please share a demo where the issue can be reproduced.

**Comment by hernanif1** [comment]
you need to force the key to change using maybe the same variable that you are setting
https://codesandbox.io/s/strange-neumann-35dsn?file=/src/App.tsx

**Comment by vydimitrov** [comment]
Hey @hernanif1, good catch, thanks for the demo. I was able to reproduce it now. I will investigate and fix it.

**Comment by vydimitrov** [comment]
Wait wait wait ... this is how React works ... I needed a few minutes to think about it before releasing that. So what happens here is that when you change the `key` of the component the component is unmounted and new instance of it is mounted. The new instance starts the animation right the way because `isPlaying` is true. The previous instance of the component is unmounted thus all functions and callbacks are removed.

I think it works as expected. Does this make sense?

**Comment by vydimitrov** [comment]
But anyhow, thanks again @hernanif1 for taking the time to create the demo and report it. Better be this way than having an issue hidden.

**Comment by vydimitrov** [comment]
It appeared that the issue is triggered when we try to change the `isPlaying` state within the `onCompelte `handler. I will have a fix for it.
