### ISSUE TITLE
Where does requestAnimationFrame get called?

### ISSUE THREAD

**Issue by Rickardo228** [vydimitrov/react-countdown-circle-timer#60]
Hi Vasil,

Really great library, thank you!
I have been reading all of the source code for this component (web) to try to learn and understand how it works.
If you have time to answer a quick question, I'd very much appreciate it!

How does the animation work? I understand this is probably done by requestAnimationFrame or setInterval, but I can't see this called anywhere in the source. I also can't see much use of state to re-render the components. Any help would be great 👍 

Thanks again,

Ric

**Comment by Rickardo228** [comment]
Think I just found it - your other library!
import { useElapsedTime } from 'use-elapsed-time'

**Comment by vydimitrov** [comment]
Hey @Rickardo228, you are right, the component is using `useElapsedTime` library that returns the elapsed time since the animation started. That happens on every `requestAnimationFrame` and causes rerender (using `useState`) so the component can update its state and move the timer. Hope that helps you. Let me know if you have any other questions.

**Comment by vydimitrov** [comment]
I am closing this issue. Let me know if you need some more info on how thing work.
