### ISSUE TITLE
onComplete does not trigger if page is not focused

### ISSUE THREAD

**Issue by pkm52000** [vydimitrov/react-countdown-circle-timer#7]
Potentially a Chrome issue, in my brief testing I didn't experience this in Firefox.

Reproduction steps: When the timer is counting down if change tabs and come back to the tab after you would expect onComplete to be fired, only then is the callback triggered.

**Comment by vydimitrov** [comment]
I was able to reproduce it and I guess that it is because of `setTimeout` here https://github.com/vydimitrov/use-elapsed-time/blob/master/src/index.js#L32

I will investigate further and try to fix it.

**Comment by vydimitrov** [comment]
Chrome will pause `requestAnimationFrame` until the moment the tab gets focused again. Please refer to the demo here - https://codesandbox.io/s/flamboyant-leftpad-zquqn

`react-countdown-circle-timer` is using `requestAnimationFrame` to get the elapsed time by measuring the time between two frames. This is actually the recommended way to measure elapsed time in JavaScript. So what happens here is that Chrome pauses `requestAnimationFrame`  and when the tab gets focused again `react-countdown-circle-timer` measures the time before the tab looses focus and after it gets it back. When that time is more than the duration provided it will move the timer to "completed state" and call `onComplete`. This is why you though that  `onComplete` gets called when the tab gets focused again but in fact the whole animation was paused while the tab was not focused.

Firefox handles that differently, it seems that the animation keeps going even when the tab is not active. But if you change to a different App while the animation is running, Firefox will also pause it. 

I guess Chrome has a good reason to pause the updates when tab is not active since it is something that the user will never see. Also on most browsers inactive tabs have low priority execution and this can affect JavaScript timers. Handling time on none focused tabs is very inconsistent among browsers. 

If this behavior is critical for your App, the recommended way to handle this is to pause the timer when the tab looses focus and reset it once it gets focused again. `react-countdown-circle-timer` provides a prop `isPlaying` that you can use for that. You can read more about page visibility API here - https://levelup.gitconnected.com/introducing-the-page-visibility-api-2fe50ee3dcfa. In any other case, the countdown will be done when the elapsed time is more than the duration, regardless of the tab being focused or not. 

Hope this helps to solve your problem.

**Comment by dani24gl** [comment]
Hi, the `onComplete` function is not being called when the Android app is in the background. How can I fix that?

**Comment by vydimitrov** [comment]
You can read about it here - https://github.com/vydimitrov/react-countdown-circle-timer/issues/70

**Comment by WillSmithTE** [comment]
Hi, my use case is I run the timer multiple times with different time lengths. E.g. I might run it for 20 seconds, then 15 seconds, then 30. Each time the timer completes I play some audio and expect the next timer to start immediately. Obviously this is a problem when I change tabs, because I want to keep cycling through each timer length and hearing the sounds in the background. I understand your reasoning above, but do you have any suggested workarounds for how I might get this behaviour in the background?

Thanks for the library and the maintenance.

**Comment by vydimitrov** [comment]
Hey @WillSmithTE, are you sure that you can play sound from none active tab? The only way I can thing off now is to stop the timer when the tab changes visibility, get the remaining time and star a loop using setInterval, which should run even when the tab is not active. Once the user comes back start the timer again with the remaining time from the loop.

**Comment by benjitastic** [comment]
Running into this issue as well. One option could be to move the countdown timer logic into a web worker which doesn't get paused when tab is backgrounded. Something like this: https://www.npmjs.com/package/worker-interval

For now I will pause/reset the timer with window visibility listeners.

**Comment by sushantdhiman** [comment]
With `Chrome 103.0.5060.134 - Desktop`, as per my tests, inactive tab honors `setTimeout` while `requestAnimationFrame` is paused. So using `setTimeout` along with `useEffect` should work for inactive tabs.
