### ISSUE TITLE
Version 2.4 is not working with React 17.1

### ISSUE THREAD

**Issue by birkanozer** [vydimitrov/react-countdown-circle-timer#76]
Here you can try. Version 2.2.0 and beyond is not working with React 17.1

https://codesandbox.io/s/not-working-fgvkb

**Comment by vydimitrov** [comment]
Hey, the issue is not related to React 17 at all. The problem with that Codesandbox is that the `elapsedTime`, which we get in the `children` prop, is formatted from milliseconds to seconds. This was the case in some very old versions of the library where we were getting the `elapsedTime` in milliseconds. Not while a ago, I updated the library so now we work only in seconds.

You can check this working demo - https://codesandbox.io/s/musing-davinci-mqssz?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.js:1252-1263

Let me know if you have any other questions.
